services:
  postgresql:
    type: postgresql:16
    configuration:
      extensions:
        - vector

applications:
  app:
    stack:
      - "nodejs@22"
      - "python@3.12"
    relationships:
      db: "postgresql:postgresql"
    mounts:
      "/.npm":
        source: "storage"
        source_path: "npm"
      "/.cache":
        source: "storage"
        source_path: "cache"
    web:
      commands:
        start: "npx next start -p $PORT"
    hooks:
      build: |
        set -eux
        npm install
        npx prisma generate
        npm run build
        cd vectorize/
        pip install -r requirements.txt
      post_deploy: |
        set -eux
        cd vectorize/
        python vectorize.py

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
