services:
  postgresql:
    type: postgresql:16
    configuration:
      extensions:
        - vector

applications:
  watches-next:
    stack:
      - "nodejs@22"
      - "python@3.12"
      - "openssl"
    source:
      root: "/"
    relationships:
      postgresql: "postgresql:postgresql"
    mounts:
      "/.npm":
        source: "storage"
        source_path: "npm"
      "/.cache":
        source: "storage"
        source_path: "cache"
    web:
      commands:
        start: "npx next start -p $PORT"
      upstream:
        socket_family: tcp
      locations:
        "/":
          passthru: true
    hooks:
      build: |
        set -eux
        npm i
        npx prisma generate
        npm run build
        cd vectorize/
        pip install -r requirements.txt
      post_deploy: |
        set -eux
        cd vectorize/
        python vectorize.py

routes:
  "https://{default}/":
    type: upstream
    upstream: "watches-next:http"
